"""Add sold field

Revision ID: 3a4baaa58bf2
Revises: 5fa32f30b75a
Create Date: 2025-01-19 20:37:45.404302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a4baaa58bf2'
down_revision: Union[str, None] = '5fa32f30b75a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('sold', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'sold')
    # ### end Alembic commands ###
